name: Shane McIntosh - Asst. Professor
markdown: redcarpet
pygments: true
taglist: ["build-systems", "software-quality", "software-evolution", "code-review", "build-performance", "software-licensing", "integration", "code-cloning", "sonification", "web-applications", "static-analysis"]
venuelist: ["ICSE", "FSE", "ASE", "ICSME", "MSR", "SANER", "EMSE", "AUSE", "IWPSE", "WSE", "Theses"]
yearlist: [2016, 2015, 2014, 2012, 2011, 2010]
