- title: Program Committee Co-chair
  host:
    - International Workshop on Release Engineering (RELENG 2016)
    - International Workshop on Empirical Software Engineering in Practice (IWESEP 2016)

- title: Program Committee
  host:
    - International Conference on Software Maintenance and Evolution (ICSME 2017)
    - International Conference on Object-Oriented Programming, Systems, Languages, and Applications (OOPSLA 2017)
    - International Conference on Mining Software Repositories (MSR 2017)
    - International Conference on Evaluation and Assessment in Software Engineering (EASE 2017)
    - International Workshop on Empirical Software Engineering in Practice (IWESEP 2017)
    - International Workshop on Software Analytics (SWAN 2016)
    - International Conference on Software Maintenance and Evolution (ICSME 2016)
    - Working Conference on Mining Software Repositories (MSR 2016)
    - International Workshop on Empirical Software Engineering in Practice (IWESEP 2014)

- title: Formal Tool Demonstrations Program Committee
  host:
    - International Symposium on the Foundations of Software Engineering (FSE 2017)
    - International Conference on Program Comprehension (ICPC 2016)
    - International Conference on Software Analysis, Evolution, and Reengineering (SANER 2016)
    - International Conference on Program Comprehension (ICPC 2015)
    - International Conference on Software Maintenance and Evolution (ICSME 2014)
    - International Conference on Program Comprehension (ICPC 2014)

- title: Artifact Evaluation Committee
  host:
    - International Symposium on the Foundations of Software Engineering (FSE 2014)

- title: Mining Challenge Committee
  host:
    - Working Conference on Mining Software Repositories (MSR 2015)

- title: Data Showcase Committee
  host:
    - Working Conference on Mining Software Repositories (MSR 2016)
    - Working Conference on Mining Software Repositories (MSR 2015)
    - Working Conference on Mining Software Repositories (MSR 2013)

- title: Reviewer
  host:
    - Transactions on Software Engineering (TSE)
    - Empirical Software Engineering (EMSE)
    - Automated Software Engineering (AUSE)
    - Information and Software Technology (IST)
    - Journal of Software and Systems (JSS)
    - IEEE Software
