- title: Tool Demo Program Committee Member
  host: International Conference on Software Maintenance and Evolution (ICSME 2014)
  url: http://www.icsme.org/

- title: Program Committee Member
  host: International Workshop on Empirical Software Engineering in Practice (IWESEP 2014)
  url: http://iwesep2014.naist.jp/

- title: Artifact Evaluation Committee Member
  host: International Symposium on the Foundations of Software Engineering (FSE 2014)
  url: http://fse22.gatech.edu/

- title: Tool Demo Program Committee Member
  host: International Conference on Program Comprehension (ICPC 2014)
  url: http://icpc2014.usask.ca/PosterAndToolDemo.aspx

- title: Additional Reviewer
  host: Working Conference on Mining Software Repositories (MSR 2014)
  url: http://2014.msrconf.org/

- title: Additional Reviewer
  host: International Conference on Software Engineering (ICSE 2014)
  url: http://2014.icse-conferences.org/

- title: Additional Reviewer
  host: Working Conference on Mining Software Repositories (MSR 2013)
  url: http://2013.msrconf.org/

- title: Additional Reviewer
  host: IEEE Software
  url: http://www.computer.org/portal/web/computingnow/software
